on: [push]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2.2']
    name: Build (GHC ${{ matrix.ghc }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal test